[project]
name = "learn_fastapi"
version = "0.1.0"
description = "Add a short description here"
authors = ["deepthought <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
fastapi = ">=0.109.2,<0.110"
nodejs = ">=20.9.0,<20.10"
uvicorn-standard = ">=0.27.1,<0.28"
